#ifndef _SYNTAX_H_
#define _SYNTAX_H_

enum {
    VALID_CODE,
    MISMATCHED_PARENTHESES,
    UNKNOWN_KEYWORD,
    UNKNOWN_SYMBOL,
    UNDEFINED_FUNCTION,
    UNINITIALIZED_VARIABLE
} return_types;

#endif // _SYNTAX_H_
